### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Junni2704** [Junni2704/BudgetBuddy-Capstone-Project#10]
User can **search by months.**

**Comment by mtrigo-fol** [comment]
Search **what**?

**Comment by Junni2704** [comment]
User can search transaction or any addition of expense.

**Comment by mtrigo-fol** [comment]
> User can search transaction or any addition of expense.

Not sure what you mean with "addition of expense", but the feature description then should probably be closer to

"User can search for expenses (or transactions) created in a given month"

Not sure how your app differentiates between an expense or transaction (or if it does at all).

**Comment by Junni2704** [comment]
Wasnt Able to Complete The Task As we got stuck at one place and tried looking for solution but we wasnt able to find one
