### ISSUE TITLE
Swipe calendar

### ISSUE THREAD

**Issue by Junni2704** [Junni2704/BudgetBuddy-Capstone-Project#11]
User can **swipe calendar on daily basis.**

**Comment by mtrigo-fol** [comment]
What is this feature? What does it even mean? What is the user doing and how is the app responding?

**Comment by Junni2704** [comment]
Sir this means that the user can see the daily transaction on the basis of swiping the calendar dates.  It means that you can go back on the previous dates for transaction and if you want to add a new transaction for future you can swipe the date carousel on the main screen and add or perform any operation.

**Comment by mtrigo-fol** [comment]
> Sir this means that the user can see the daily transaction on the basis of swiping the calendar dates. It means that you can go back on the previous dates for transaction and if you want to add a new transaction for future you can swipe the date carousel on the main screen and add or perform any operation.

You should update the issue's description to match this
