### ISSUE TITLE
Select Account

### ISSUE THREAD

**Issue by Junni2704** [Junni2704/BudgetBuddy-Capstone-Project#5]
User can **select the account type.**

**Comment by mtrigo-fol** [comment]
Seems like this feature should be described as the user creating an account in the first place? Not sure what "the account" means here for the "type"

**Comment by Junni2704** [comment]
Sir selecting account type is like most of the people have different accounts for different purposes, For eg. user have to add an expense for grocery with a specific bank account so he can select with what account he have to pay for maintaining the history

**Comment by mtrigo-fol** [comment]
> Sir selecting account type is like most of the people have different accounts for different purposes, For eg. user have to add an expense for grocery with a specific bank account so he can select with what account he have to pay for maintaining the history

Then the user-story description should be something like "User can select the account type when adding a new expense"
